### ISSUE TITLE
Update to nan 2 for Node.js 4.0.0 compatibility.

### ISSUE THREAD

**Issue by ChALkeR** [btrask/node-socketwatcher#9]
Adding to the list: https://github.com/nodejs/node/issues/2798.
Related: #8.

**Comment by Codelica** [comment]
Also related to comments in #8.  Would be very grateful for a Nan update. :+1:

**Comment by megastef** [comment]
+1 There is tool: https://github.com/nodejs/nan/blob/master/tools/1to2.js

**Comment by ide** [comment]
Could someone who's familiar with the socketwatcher library (that is, has directly used it before) help review my PR by testing it in your own applications? There are no tests for this project so it is helpful if you could throw code at it.
